[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/qgwyspks"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
